[project]
name = "stock-forecast"
description = "Stock forecast using machine learning"
version = "0.1.0"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
